export const COMO_CONFESSAR_INTRO = `É importante se preparar bem para que a confissão tenha o efeito desejado: o perdão dos pecados e renovar a amizade com Deus. Antes de tudo é preciso ser católico e batizado. Em seguida, lembrar com esforço razoável os pecados cometidos desde a última confissão, estar verdadeiramente arrependido e buscar não mais recair neles.`

export const COMO_CONFESSAR_PASSOS = [
  "Responder ao confessor há quanto tempo não se confessa (aproximadamente). A Igreja obriga a confissão sob pena de pecado grave no mínimo 1 vez por ano, mas o conveniente é fazê-lo 1 vez por mês ou o quanto antes caso se tenha cometido falta grave.",
  "Dizer quais pecados cometeu (os próprios, não os dos outros!), dos mais importantes aos menos importantes. O obrigatório é falar todos os pecados graves quanto ao tipo e o número (aproximado) de vezes. Caso não haja pecados graves, confessar pecados veniais sinceramente arrependidos.",
  "Escutar o que o confessor tem a dizer (perguntas a esclarecer, remédios a aplicar).",
  "Memorizar a penitência recebida.",
  "Rezar a fórmula do Ato de Contrição em voz audível ao confessor.",
  "Esperar o confessor dar o sinal para sair.",
  "Realizar o quanto antes a penitência imposta para não a esquecer.",
]

export const COMO_CONFESSAR_OBSERVACOES = [
  "Se o padre não der a absolvição, entender bem o motivo para tal.",
  `Se o padre esqueceu a fórmula da absolvição, lembrá-lo que é: "Eu te absolvo de teus pecados em nome do Pai + e do Filho e do Espírito Santo. Amém."`,
  `Se o padre usa uma fórmula de absolvição errada ou confusa (por exemplo, dizendo apenas "Que Deus o abençoe"), é melhor buscar outro padre.`,
]

export const ORACAO_ANTES_EXAME = `Senhor Deus onipotente, prostrado humildemente diante da vossa divina majestade, vos rendo infinitas graças por todos os benefícios que de vossa inefável bondade tenho recebido, e em particular por me terdes criado, conservado, remido e cumulado de tantos bens e mercês, muitos dos quais eu ignoro. Rogo-vos, Senhor, humildemente, que vos digneis conceder-me luz abundante para conhecer todas as faltas e pecados, com que vos tenho ofendido, e graça eficaz para me arrepender e me emendar.`

export type ExameSection = {
  titulo: string
  subtitulo?: string
  intro?: string
  itens: string[]
  tag?: string
  badgeVariant?: 'capital'
  grupoCabecalho?: string
}

export const EXAME_SECTIONS: ExameSection[] = [
  {
    titulo: "Antes dos Mandamentos",
    tag: "✦",
    itens: [
      "Há quanto tempo você fez sua última confissão?",
      "Você recebeu absolvição?",
      "Você cumpriu sua penitência?",
      "Você deliberadamente ocultou um pecado mortal, ou confessou sem arrependimento verdadeiro, ou sem firme propósito de correção, ou sem a intenção de cumprir sua penitência?",
      "Você, após essa má confissão, recebeu a Santa Comunhão em estado de pecado mortal?",
      "Quantas dessas Confissões e Comunhões sacrílegas você fez?",
      "Você, em estado de pecado mortal, recebeu qualquer outro Sacramento?",
    ],
  },
  {
    titulo: "I Mandamento",
    subtitulo: "Não terás outro Deus diante de Mim",
    tag: "I",
    itens: [
      "Negligência na oração (distrações voluntárias, orações omitidas)",
      "Ficar mais de um mês sem rezar",
      "Ingratidão para com Deus",
      "Preguiça espiritual (acídia)",
      "Ódio a Deus ou à Igreja Católica",
      "Tentar a Deus (expondo-se voluntariamente a perigo para a alma, a vida ou saúde sem causa grave)",
      "Não se comportar adequadamente em uma Igreja (não fazer a genuflexão para o Santíssimo Sacramento ao entrar ou sair, etc.)",
      "Excessivo apego a coisas/criaturas (animais, esportes, ídolos da TV, música, cinema; amor desordenado pelo dinheiro, prazer ou poder)",
      "Idolatria (adorar falsos deuses ou honrar uma criatura no lugar de Deus: Satanás, a ciência, os ancestrais, o país)",
      "Superstição (atribuir poderes a coisas criadas que não os possuem — por ignorância pode ser pecado venial)",
      "Hipnotismo (sem causa grave)",
      "Adivinhação (consultar horóscopos, astrologia, leitura da mão, tarot, ver a sorte, etc.)",
      "Atribuição de importância indevida a sonhos, presságios, destino",
      "Práticas de magia (branca ou negra) ou feitiçaria (bruxaria, vodu)",
      "Usar amuletos",
      "Jogar com quadros Ouija ou mesas giratórias",
      "Espiritismo (falar com os espíritos)",
      "Sacrilégio (profanar ou tratar indignamente os sacramentos, particularmente a Santa Eucaristia, vasos sagrados, estátuas ou lugares consagrados a Deus)",
      "Receber a Santa Eucaristia em estado de pecado mortal",
      "Simonia (comprar ou vender coisas espirituais)",
      "Uso profano ou supersticioso de objetos abençoados",
      "Materialismo prático (agir como se somente coisas materiais importassem)",
      "Ateísmo em geral (rejeitar, negar ou duvidar da existência de Deus na teoria ou na prática, ignorando-O na vida diária)",
      "Agnosticismo (declarar impossível conhecer ou afirmar a existência de Deus)",
      // Pecados contra a fé
      "Dúvida voluntária de algum artigo da fé",
      "Ignorância deliberada das verdades da fé que devem ser conhecidas",
      "Falar contra uma doutrina da Igreja Católica",
      "Negligência em se instruir na fé segundo o próprio estado",
      "Credulidade imprudente (dar crédito muito facilmente a revelações privadas ou acreditar em revelações condenadas pela Igreja)",
      "Apostasia (abandono completo da fé)",
      "Heresia (negar uma ou mais verdades da fé)",
      "Indiferentismo (acreditar que uma religião é tão boa quanto as demais, e que todas são igualmente verdadeiras e agradáveis a Deus)",
      "Ler ou fazer circular escritos contrários à fé Católica, comprometendo a própria fé ou a alheia",
      "Ouvir músicas cuja letra é contrária à religião católica",
      "Permanecer em silêncio quando questionado sobre a própria fé (pecado grave quando interrogado pela autoridade legítima)",
      "Tomar parte em culto herético ou cismático",
      "Ouvir a pregação de ministro de falsa religião",
      "Aderir ou apoiar grupos maçônicos ou sociedades proibidas (teosofia, rosa-cruz, etc.)",
      // Pecados contra a esperança
      "Desespero da misericórdia de Deus (desistir de toda esperança de salvação — diferente do mero sentimento de desânimo)",
      "Falta de confiança no poder da Graça de Deus para apoiar nos apuros ou tentações",
      "Não recorrer a Deus e aos santos nos momentos de tentação",
      "Nenhum desejo de possuir a felicidade eterna no paraíso ou após a vida terrena",
      "Presunção (esperar pela salvação sem ajuda de Deus ou pressupor o perdão sem conversão)",
      "Presunção da misericórdia de Deus ou de certas práticas de piedade para continuar no pecado",
      "Recusa de qualquer dependência de Deus",
      // Pecados contra a caridade
      "Não praticar atos de caridade em intervalos regulares durante a vida, particularmente em momentos de necessidade",
      "Egoísmo (preocupar-se somente consigo mesmo, ser interesseiro, gostar de receber elogios)",
      "Pensamentos deliberadamente revoltosos contra Deus",
      "Jactância: alardear o próprio pecado ou orgulhar-se dele",
      "Violar a lei de Deus ou omitir boas obras por respeito humano",
      "Impaciência diante das adversidades e provações de Deus",
    ],
  },
  {
    titulo: "II Mandamento",
    subtitulo: "Não tomarás o nome do Senhor em vão",
    tag: "II",
    itens: [
      "Desonra de Deus por uso profano ou desrespeitoso de seu Nome, ou do Santo Nome de Jesus Cristo, da Santíssima Virgem Maria e dos santos",
      "Blasfêmia (insultar a Deus, Nosso Senhor Jesus Cristo, a Igreja Católica, a Santíssima Virgem Maria ou os santos por palavras ou gestos)",
      "Ouvir músicas blasfemas",
      "Perjúrio (prometer algo sob juramento sem ter intenção de cumpri-lo, ou quebrar promessa feita sob juramento — grave ou não conforme a gravidade)",
      "Fazer juramentos falsos ou desnecessários (chamar a Deus como testemunha de uma mentira)",
      "Amaldiçoar a si mesmo ou a outros com intenção real (há pecado grave)",
      "Murmurar, reclamando das disposições da providência divina",
      "Quebrar votos ou promessas feitas a Deus (pode ser grave conforme a importância do voto)",
      "Irreverência na Igreja (falar durante a Missa sem razão suficiente, distrair os demais, vestir-se de forma inapropriada ou qualquer outro comportamento impróprio)",
    ],
  },
  {
    titulo: "III Mandamento",
    subtitulo: "Lembra-te de santificar o dia do Senhor",
    tag: "III",
    itens: [
      "Omissão da oração e do culto divino",
      "Todo trabalho servil desnecessário no Domingo ou Dias Santos de Guarda",
      "Comércio desnecessário nos Domingos e Dias de Guarda (comprar e vender)",
      "Profanar estes dias frequentando companhia impiedosa, com diversões pecaminosas, jogos de azar, dança indecente ou excessos com bebida",
    ],
  },
  {
    titulo: "IV Mandamento",
    subtitulo: "Honra teu pai e tua mãe",
    tag: "IV",
    intro: "Este mandamento regula nossas obrigações para com os pais, filhos, cônjuge, superiores civis e eclesiásticos, empregadores, empregados, professores e estudantes.",
    itens: [
      // Para os pais
      "[Para pais] Odiar ou amaldiçoar os filhos",
      "[Para pais] Dar escândalo a eles ao praguejar, beber ou agir mal",
      "[Para pais] Deixar que os filhos cresçam na ignorância, indolência ou pecado",
      "[Para pais] Demonstrar parcialidade habitual entre os filhos sem causa",
      "[Para pais] Adiar o batismo de uma criança por mais de um mês (em geral, pecado mortal)",
      "[Para pais] Negligência no cuidado da saúde corporal, instrução religiosa, companhias, leituras e diversões dos filhos",
      "[Para pais] Não corrigir os filhos quando necessário; ou ser duro e cruel nas correções",
      "[Para pais] Enviar filhos para escolas protestantes, esotéricas ou de outra religião",
      "[Para pais] Negligência em conduzi-los à Missa nos Domingos e Dias Santos de Guarda e na recepção dos sacramentos",
      // Para os filhos
      "[Para filhos] Toda forma de raiva ou aversão contra os pais e demais superiores legítimos",
      "[Para filhos] Desdenhar, desejar mal, ameaçar ou levantar a mão contra os pais",
      "[Para filhos] Afligir os pais por ingratidão ou má conduta; provocá-los à raiva",
      "[Para filhos] Ofender, insultar ou não ajudar os pais em suas necessidades",
      "[Para filhos] Desprezo ou desobediência às ordens legítimas dos pais (sobretudo quanto a más companhias, diversões e deveres de estado)",
      // Para cônjuges
      "[Para cônjuges] Maltrato (tratar o cônjuge sem consideração pelo bem-estar e sem caridade)",
      "[Para cônjuges] Colocar obstáculos ao cumprimento dos deveres religiosos do cônjuge",
      "[Para cônjuges] Negar-se ao débito conjugal sem causa realmente justa",
      "[Para cônjuges] Falta de paciência ou dureza quanto às faltas um do outro; ciúmes despropositados",
      "[Para cônjuges] Negligência nos deveres domésticos; mau humor, aborrecimento sem motivo",
      "[Para cônjuges] Palavras injuriosas; negligência em prover o sustento da família por preguiça ou timidez",
      // Súditos da Igreja e do Estado
      "[Súditos] Desrespeitar e desobedecer aos superiores espirituais (Papa, bispos, padres) em suas ordens legítimas",
      "[Súditos] Comportar-se de modo soberbo ou insultante em relação a eles; recusar rezar por eles",
      "[Súditos] Deixar de rezar pelo próprio país e pelo governo",
      "[Súditos] Colocar o país acima de Deus; tomar parte em questões subversivas",
      "[Súditos] Juntar-se a associações comunistas ou liberais; resistir às autoridades legais",
      "[Súditos] Votar em partidos comunistas ou socialistas",
      // Para empregadores
      "[Empregadores] Não permitir aos empregados tempo razoável para os deveres religiosos",
      "[Empregadores] Dar mau exemplo ou permitir que outros o façam",
      "[Empregadores] Não pagar os salários legais; não cuidar dos empregados na doença",
      "[Empregadores] Demitir arbitrariamente sem causa",
      // Para empregados
      "[Empregados] Desrespeito, falta de obediência ao que se obrigou por contrato justo",
      "[Empregados] Perda de tempo no trabalho (sobretudo com internet); negligência no trabalho",
      "[Empregados] Dano à propriedade do empregador por desonestidade, descuido ou negligência",
      "[Empregados] Violar políticas do local de trabalho sem razão suficiente",
      // Para professores e estudantes
      "[Professores] Negligência no progresso dos alunos; punição injusta ou excessiva; parcialidade",
      "[Professores] Ensinar máximas falsas ou incertas como verdadeiras",
      "[Estudantes] Desrespeito, desobediência ou teimosia para com os professores",
      "[Estudantes] Indolência, preguiça, perda de tempo e distrações inúteis",
    ],
  },
  {
    titulo: "V Mandamento",
    subtitulo: "Não matarás",
    tag: "V",
    itens: [
      "Causar morte ou lesão física de alguém por ação própria, participação, instigação, conselho, consentimento ou silêncio",
      "Ter a intenção de matar alguém",
      "Assassinato",
      "Realizar um aborto; ajudar alguém a procurar um aborto (incorre em excomunhão se o aborto se consumar)",
      "Eutanásia ou retirar meios ordinários de um paciente terminal ou moribundo",
      "Suicídio; tentativa de suicídio; sérios pensamentos de cometer suicídio",
      "Brigar, rixas, ódio, desejo de vingança",
      "Tortura humana",
      "Gula (beber ou comer em excesso)",
      "Embriaguez (em que grau?)",
      "Abuso de álcool, medicamentos ou drogas",
      "Colocar em perigo a vida de outros (beber e dirigir, dirigir muito rápido, etc.)",
      "Colocar em risco a própria vida ou membro do corpo sem razão suficiente (acrobacias arriscadas, roleta russa, etc.)",
      "Descuido em deixar expostos venenos, drogas perigosas, armas, etc.",
      "Mutilação do corpo (vasectomia, ligadura de trompas — trata-se de pecado mortal; buscar reversão se há possibilidade de fertilidade)",
      "Histerectomia (sem causa médica suficiente)",
      "Inseminação artificial ou fertilização in vitro (trata-se de pecado mortal)",
      "Tomar contraceptivos abortivos (pílulas e outros — trata-se de pecado mortal, mesmo com motivos legítimos para evitar filhos)",
      "Uso de métodos profiláticos ou de barreira para evitar a gravidez",
      "Utilizar métodos naturais para evitar filhos com mentalidade contraceptiva",
      "Pesquisas científicas imorais e suas aplicações",
      "Mau exemplo ou escândalo, levando outros a pecar",
      "Desrespeito pelos moribundos ou pelos mortos",
      "Não tentar evitar a guerra",
      "Mostrar aversão ou desprezo pelos outros; recusar falar com outros quando cumprimentado",
      "Ignorar ofertas de reconciliação, especialmente entre parentes",
      "Fomentar um espírito que não perdoa o próximo",
      "Zombaria, escárnio, insultos, ações ou palavras irritantes",
      "Tristeza pela prosperidade alheia; alegrar-se pela miséria alheia",
      "Inveja pela atenção dada aos outros; comportamento tirânico",
      "Induzir os outros ao pecado pela palavra ou pelo exemplo",
      "Prejudicar a própria saúde pelo excesso de indulgência",
      "Dar álcool aos outros sabendo que irão abusar",
      "Vício em jogos de azar que coloca em perigo o sustento próprio ou da família",
      "Causar morte ou sofrimento desnecessário aos animais",
    ],
  },
  {
    titulo: "VI Mandamento",
    subtitulo: "Não cometerás adultério",
    tag: "VI",
    intro: "Mencionar as circunstâncias que mudam a natureza do pecado: o sexo da outra pessoa, o parentesco, o estado (próprio e do outro) de casado, solteiro ou vinculado a um voto.",
    itens: [
      "Impureza e imodéstia nas palavras, nos olhares e nas ações, seja sozinho ou com outros",
      "Contar ou ouvir piadas sujas; falar ou ouvir (consentindo) coisas indecentes ou com duplo sentido",
      "Vangloriar-se da própria imoralidade",
      "Utilizar roupas imodestas (minissaias, calças apertadas, decotes arrojados, blusas e saias transparentes, biquínis, etc.)",
      "Comprar, alugar ou assistir filmes, programas de TV ou ler livros, revistas ou outras coisas indecentes (não somente pornografia, mas tudo que contenha impurezas)",
      "Expor-se voluntariamente a ocasiões de pecado (curiosidade pecaminosa, companhia perigosa, locais perigosos, diversões ou danças indecentes, familiaridade indevida com pessoas do sexo oposto)",
      "Manter companhia pecaminosa ou morar com alguém que não é o cônjuge",
      "Ser tentação para os outros pelo modo de falar, comportar, vestir ou insinuar-se",
      "Ouvir música de letra indecente ou cujo ritmo favoreça a sensualidade",
      "Masturbação (é habitual?)",
      "Fornicação (sexo antes do casamento)",
      "Prostituição",
      "Sodomia (práticas homossexuais)",
      "Outras práticas contrárias à natureza",
      "Adultério (também em pensamentos)",
      "Divórcio",
      "Poligamia",
      "Incesto",
      "Abuso sexual",
      "Estupro",
      "Beijo sensual prolongado",
      "Carícias ou preliminares fora do matrimônio ou dentro dele sem ordenação à consumação do ato conjugal natural, com perigo de polução",
      "Ato conjugal consumado de modo inapto à procriação",
      "Negar o débito conjugal sem razão realmente legítima",
      "Danças imodestas",
      "Namoro sem tomar as devidas precauções para guardar a pureza e a fé",
      "Namoro sem maturidade suficiente ou sem intenção de casar-se",
    ],
  },
  {
    titulo: "VII Mandamento",
    subtitulo: "Não roubarás",
    tag: "VII",
    intro: "É preciso dizer ao sacerdote — o mais exatamente possível — o valor do que foi furtado/roubado ou a quantidade dos danos, de modo que o padre possa julgar se os pecados são mortais ou não. Sem a restituição ou firme propósito de fazê-la, o pecado não será perdoado.",
    itens: [
      "Roubo (quanto?)",
      "Pequenos furtos (tomar coisas do trabalho sem direito ou dinheiro da família sem permissão)",
      "Trapacear",
      "Plágio",
      "Quebra de regulamentação de direito autoral (fotocopiar sem autorização ou com fins comerciais)",
      "Manter consigo objetos emprestados ou perdidos sem tentar razoavelmente restituí-los",
      "Possessão de bens ilícitos",
      "Aconselhar ou pedir a alguém que prejudique outra pessoa ou danifique seus bens",
      "Danificar por descuido ou malícia a propriedade alheia",
      "Ocultação de fraude, roubo ou dano quando se tem dever de dar a informação",
      "Sonegação de impostos justos",
      "Fraude comercial, desonestidade na política e nos negócios",
      "Não pagar dívidas justas no tempo correto sem fazer os esforços e sacrifícios necessários",
      "Não fazer reparação ou compensação a alguém que sofre por danos injustos",
      "Aumentar os preços tirando proveito da ignorância ou necessidade alheia",
      "Usura (emprestar dinheiro a altos juros a alguém em dificuldade financeira)",
      "Especulação que manipula artificialmente o preço dos bens para lucrar com prejuízo dos demais",
      "Corrupção (influenciar o julgamento daqueles que devem decidir em questões legais)",
      "Aceitar ou oferecer suborno",
      "Apropriação e uso de bens comuns de uma empresa para fins privados",
      "Trabalho mal feito",
      "Pagar salários injustos ou desprover empregado de benefícios devidos",
      "Falsificação de cheques e faturas",
      "Emitir cheques sabendo que não há fundo suficiente para cobri-los",
      "Despesas e gastos excessivos ou desnecessários",
      "Não manter promessas ou acordos contratuais moralmente justos",
      "Jogar e apostar (privando-se dos meios necessários de vida para si ou para outros)",
    ],
  },
  {
    titulo: "VIII Mandamento",
    subtitulo: "Não darás falso testemunho",
    tag: "VIII",
    itens: [
      "Mentir (a mentira chegou a prejudicar alguém, gravemente ou não?)",
      "Dizer palavrões, grosserias",
      "Vangloriar-se",
      "Lisonja (bazófia)",
      "Hipocrisia",
      "Exagero",
      "Ironia",
      "Sarcasmo",
      "Detração (revelar, sem justa causa, faltas verdadeiras escondidas do próximo)",
      "Calúnia ou difamação (revelar falsos defeitos do próximo; contar histórias ou espalhar rumores) — é preciso restituir a boa fama injustamente prejudicada",
      "Criticar os outros; escutar com prazer os outros sendo criticados",
      "Fazer fofocas",
      "Desonrar injustamente outra pessoa em sua presença (injúria)",
      "Julgamento precipitado (acreditar firmemente, sem razão suficiente, que alguém possui um defeito moral ou fez algo errado)",
      "Revelar segredos",
      "Publicar segredos que causem descrédito, sem causa proporcionalmente grave (mesmo se for verdade)",
      "Recusar ou demorar em restituir o bom nome manchado",
      "Acusações sem fundamento",
      "Suspeitas infundadas e julgamentos precipitados sobre os outros em nossa própria mente",
    ],
  },
  {
    titulo: "IX Mandamento",
    subtitulo: "Não cobiçarás a mulher do próximo",
    tag: "IX",
    intro: "O nono mandamento proíbe todo pensamento e desejo impuro com os quais nos comprazemos deliberadamente. O penitente deve ter em mente que se deleitar deliberadamente ou consentir em qualquer pecado listado no sexto mandamento pode ter o mesmo grau de gravidade de executá-lo de fato, isto é, trata-se de pecado mortal ou venial, segundo o pecado e conforme haja plena advertência e pleno consentimento.",
    itens: [
      "Pensamentos e desejos impuros deliberadamente consentidos",
      "Comprazer-se voluntariamente em fantasias ou pensamentos de luxúria",
      "Consentir em paixões ou pensamentos impuros quando vêm à mente",
      "Buscar deliberadamente ocasiões de pensamentos impuros (filmes, músicas, imagens)",
    ],
  },
  {
    titulo: "X Mandamento",
    subtitulo: "Não cobiçarás os bens do próximo",
    tag: "X",
    itens: [
      "Inveja (desejar os bens de outrem)",
      "Ciúmes (zelo para manter um bem longe dos outros)",
      "Ganância e desejo sem limites de ter bens materiais (avareza)",
      "Desejo de enriquecer a qualquer preço",
      "Negócios ou profissões que esperam circunstâncias desfavoráveis aos outros para lucrar pessoalmente",
      "Inveja dos sucessos, talentos, bens espirituais ou temporais alheios",
      "Desejar cometer injustiça prejudicando alguém para obter seus bens temporais",
      "Alegrar-se ou consentir nos pecados contra o sétimo mandamento",
    ],
  },
  {
    titulo: "Preceitos da Santa Igreja",
    tag: "✦",
    itens: [
      "I Preceito — Faltar à Santa Missa nos Domingos e Dias Santos de Guarda sem razão suficiente",
      "I Preceito — Chegar atrasado à Missa sem razão suficiente (dependendo da qualidade e quantidade do atraso, pode ser pecado leve ou grave)",
      "II Preceito — Não jejuar na Quarta-feira de Cinzas e Sexta-feira Santa (obriga dos 18 aos 59 anos)",
      "II Preceito — Não se abster de carne nas sextas-feiras e na Quarta-feira de Cinzas (obriga a partir dos 14 anos)",
      "III Preceito — Não se confessar de pecados mortais ao menos uma vez por ano",
      "IV Preceito — Não receber a Santa Comunhão durante o período da Páscoa (da Quinta-feira Santa até o Domingo da Santíssima Trindade)",
      "V Preceito — Não contribuir para o sustento da Igreja e de seus ministros conforme as próprias possibilidades",
      "VI Preceito — Casar-se ou ajudar alguém a se casar sem a permissão e forma devidas da Santa Igreja",
    ],
  },
  // Os 7 Pecados Capitais
  {
    titulo: "Soberba (Orgulho)",
    subtitulo: "Amor desordenado de si mesmo acima de Deus e do próximo",
    tag: "I",
    badgeVariant: 'capital',
    grupoCabecalho: "Os 7 Pecados Capitais",
    itens: [
      "Pensar-se superior aos outros em talento, virtude ou nascimento",
      "Vangloriar-se dos próprios méritos como se fossem seus e não de Deus",
      "Arrogância e presunção nas palavras e ações",
      "Recusar reconhecer os próprios erros e defeitos",
      "Não aceitar correções, repreensões ou conselhos",
      "Menosprezar os outros por seus pecados, fraquezas ou condição social",
      "Desprezar os humildes e pobres",
      "Buscar excessivamente elogios, louvor e admiração alheia",
      "Orgulho do próprio pecado (gloriar-se nos vícios)",
      "Ambição desordenada de cargos, honras e poder",
      "Rebeldia contra a autoridade legítima por soberba",
      "Não reconhecer a Deus como fonte de todos os bens e talentos",
      "Humilhar o próximo por palavras ou ações",
      "Inveja da glória alheia nascida do orgulho",
    ],
  },
  {
    titulo: "Avareza (Ganância)",
    subtitulo: "Amor desordenado às riquezas, antepondo bens materiais a Deus e ao próximo",
    tag: "II",
    badgeVariant: 'capital',
    itens: [
      "Amor desordenado às riquezas e bens materiais",
      "Nunca estar satisfeito com o que se possui",
      "Recusar dar esmola ou ajudar os necessitados podendo fazê-lo",
      "Reter salários justos dos empregados por avareza",
      "Explorar os pobres e vulneráveis",
      "Acumular bens além do necessário por apego ao dinheiro",
      "Preferir o dinheiro a Deus, à família e ao próximo",
      "Avareza nos gastos com obras de misericórdia e com a Igreja",
      "Praticar usura (emprestar com juros abusivos)",
      "Defraudar nos negócios por amor ao lucro",
      "Não dispor os bens com justiça (testamento, heranças, dívidas)",
    ],
  },
  {
    titulo: "Luxúria (Lascívia)",
    subtitulo: "Amor desordenado dos prazeres sensuais, contrários à castidade",
    tag: "III",
    badgeVariant: 'capital',
    itens: [
      "Pensamentos e fantasias impuras consentidos voluntariamente",
      "Impureza solitária (masturbação)",
      "Relações sexuais fora do matrimônio (fornicação)",
      "Adultério (relações com pessoa casada ou sendo casado)",
      "Práticas homossexuais",
      "Outras práticas contrárias à natureza",
      "Consumir ou partilhar pornografia (filmes, fotos, textos)",
      "Conversas obscenas, piadas sujas, expressões indecentes",
      "Olhares impuros consentidos de propósito",
      "Vestir-se de modo a provocar concupiscência alheia",
      "Frequentar ambientes, companhias ou situações que favorecem a impureza",
      "Ouvir música ou assistir conteúdo que excita a sensualidade",
      "Namoro ou noivado sem cuidado da pureza",
    ],
  },
  {
    titulo: "Inveja",
    subtitulo: "Tristeza pelo bem alheio, como se esse bem fosse diminuição do próprio",
    tag: "IV",
    badgeVariant: 'capital',
    itens: [
      "Tristeza pela prosperidade, talentos ou virtudes alheias",
      "Alegrar-se com o infortúnio, fracasso ou humilhação do próximo",
      "Desejar que os outros percam o que possuem",
      "Diminuir ou negar os méritos e qualidades alheias",
      "Calúnia ou difamação motivada pela inveja",
      "Rivalidade movida por rancor e ressentimento",
      "Recusar reconhecer sinceramente as qualidades dos outros",
      "Sentir-se humilhado pelo sucesso alheio",
      "Não rezar ou não desejar o bem àqueles a quem se inveja",
      "Comparar-se constantemente aos outros de modo rancoroso",
    ],
  },
  {
    titulo: "Gula",
    subtitulo: "Amor desordenado ao prazer da comida e da bebida",
    tag: "V",
    badgeVariant: 'capital',
    itens: [
      "Comer ou beber em excesso, além do necessário",
      "Embriaguez voluntária",
      "Abuso de drogas ou substâncias por prazer",
      "Ser escravo dos prazeres da mesa, sem moderação",
      "Gastar excessivamente com comida e bebida em detrimento das obrigações",
      "Exigir alimentos muito refinados ou extravagantes por prazer indevido",
      "Comer com avidez e falta de compostura",
      "Impedir ou fugir ao jejum e à abstinência prescritos pela Igreja",
      "Comer compulsivamente como substituto emocional",
    ],
  },
  {
    titulo: "Ira (Raiva)",
    subtitulo: "Desejo desordenado de vingança que perturba a paz e ofende o próximo",
    tag: "VI",
    badgeVariant: 'capital',
    itens: [
      "Explosões de raiva descontrolada",
      "Insultos, xingamentos e palavras ofensivas proferidas com raiva",
      "Guardar rancor e recusar perdoar as ofensas recebidas",
      "Desejar mal àquele que me ofendeu",
      "Buscar vingança pelas próprias mãos",
      "Impaciência com as fraquezas, defeitos e erros alheios",
      "Murmurar e reclamar com amargura e rancor",
      "Perturbação da paz familiar por causa de ira descontrolada",
      "Ódio ao próximo",
      "Recusar a reconciliação quando oferecida",
      "Violência verbal ou física motivada por ira",
      "Ira contra Deus pelas provações ou dificuldades da vida",
    ],
  },
  {
    titulo: "Preguiça (Acídia)",
    subtitulo: "Tristeza espiritual e negligência nas obrigações para com Deus e o próximo",
    tag: "VII",
    badgeVariant: 'capital',
    itens: [
      "Negligência na oração, na Missa e nos sacramentos por preguiça",
      "Abandono da vida de graça por comodismo espiritual",
      "Não praticar obras de misericórdia podendo fazê-lo",
      "Negligência nas obrigações do próprio estado (família, trabalho, estudo)",
      "Fuga das responsabilidades e deveres",
      "Tristeza espiritual persistente, desânimo e apatia na vida de fé",
      "Não corrigir os próprios defeitos por preguiça ou comodismo",
      "Adiar conversão, confissão ou obras boas sem motivo sério",
      "Não ajudar o próximo quando se pode sem grande sacrifício",
      "Preguiça no estudo da fé e na formação espiritual",
      "Vício na ociosidade, entretenimento excessivo ou fuga da realidade",
    ],
  },
]

export const ATO_DE_CONTRICAO = `Meu Deus,\neu me arrependo,\nde todo o coração,\nde Vos ter ofendido,\nporque sois tão bom e amável.\nPrometo, com a Vossa graça,\nesforçar-me para não mais pecar.\nMeu Jesus, Misericórdia.`

export const FORMULA_ABSOLVICAO = `Eu te absolvo de teus pecados em nome do Pai + e do Filho e do Espírito Santo. Amém.`
