export const COMO_CONFESSAR_INTRO = `É importante se preparar bem para que a confissão tenha o efeito desejado: o perdão dos pecados e renovar a amizade com Deus. Antes de tudo é preciso ser católico e batizado. Em seguida, lembrar com esforço razoável os pecados cometidos desde a última confissão, estar verdadeiramente arrependido e buscar não mais recair neles.`

export const COMO_CONFESSAR_PASSOS = [
  "Responder ao confessor há quanto tempo não se confessa (aproximadamente). A Igreja obriga a confissão sob pena de pecado grave no mínimo 1 vez por ano, mas o conveniente é fazê-lo 1 vez por mês ou o quanto antes caso se tenha cometido falta grave.",
  "Dizer quais pecados cometeu (os próprios, não os dos outros!), dos mais importantes aos menos importantes. O obrigatório é falar todos os pecados graves quanto ao tipo e o número (aproximado) de vezes. Caso não haja pecados graves, confessar pecados veniais sinceramente arrependidos.",
  "Escutar o que o confessor tem a dizer (perguntas a esclarecer, remédios a aplicar).",
  "Memorizar a penitência recebida.",
  "Rezar a fórmula do Ato de Contrição em voz audível ao confessor.",
  "Esperar o confessor dar o sinal para sair.",
  "Realizar o quanto antes a penitência imposta para não a esquecer.",
]

export const COMO_CONFESSAR_OBSERVACOES = [
  "Se o padre não der a absolvição, entender bem o motivo para tal.",
  `Se o padre esqueceu a fórmula da absolvição, lembrá-lo que é: "Eu te absolvo de teus pecados em nome do Pai + e do Filho e do Espírito Santo. Amém."`,
  `Se o padre usa uma fórmula de absolvição errada ou confusa (por exemplo, dizendo apenas "Que Deus o abençoe"), é melhor buscar outro padre.`,
]

export const ORACAO_ANTES_EXAME = `Senhor Deus onipotente, prostrado humildemente diante da vossa divina majestade, vos rendo infinitas graças por todos os benefícios que de vossa inefável bondade tenho recebido, e em particular por me terdes criado, conservado, remido e cumulado de tantos bens e mercês, muitos dos quais eu ignoro. Rogo-vos, Senhor, humildemente, que vos digneis conceder-me luz abundante para conhecer todas as faltas e pecados, com que vos tenho ofendido, e graça eficaz para me arrepender e me emendar.`

export type ExameSection = {
  titulo: string
  subtitulo?: string
  intro?: string
  itens: string[]
}

export const EXAME_SECTIONS: ExameSection[] = [
  {
    titulo: "Antes dos Mandamentos",
    itens: [
      "Há quanto tempo você fez sua última confissão?",
      "Você recebeu absolvição?",
      "Você cumpriu sua penitência?",
      "Você deliberadamente ocultou um pecado mortal, ou confessou sem arrependimento verdadeiro, ou sem firme propósito de correção, ou sem a intenção de cumprir sua penitência?",
      "Você, após essa má confissão, recebeu a Santa Comunhão em estado de pecado mortal?",
      "Quantas dessas Confissões e Comunhões sacrílegas você fez?",
      "Você, em estado de pecado mortal, recebeu qualquer outro Sacramento?",
    ],
  },
  {
    titulo: "I Mandamento",
    subtitulo: "Não terás outro Deus diante de Mim",
    itens: [
      "Negligência na oração (distrações voluntárias, poucas orações)",
      "Ficar mais de um mês sem rezar",
      "Ingratidão para com Deus",
      "Preguiça espiritual",
      "Ódio a Deus ou à Igreja Católica",
      "Tentar a Deus (expondo-se a perigo para a alma, a vida ou saúde sem causa grave)",
      "Não se comportar adequadamente em uma Igreja (não fazer a genuflexão para o Santíssimo Sacramento, etc.)",
      "Excessivo apego a coisas/criaturas (animais, esportes, ídolos, amor pelo dinheiro, prazer ou poder)",
      "Idolatria (adorar falsos deuses ou honrar uma criatura no lugar de Deus)",
      "Superstição (atribuir poderes a coisas criadas que não os possuem)",
      "Hipnotismo (sem causa grave)",
      "Adivinhação (consultar horóscopos, astrologia, leitura da mão, tarot, etc.)",
      "Atribuição de importância indevida a sonhos, presságios, destino",
      "Práticas de magia (branca ou negra) ou feitiçaria (bruxaria, vodu)",
      "Usar amuletos",
      "Jogar com quadros Ouija ou mesas giratórias",
      "Espiritismo (falar com os espíritos)",
      "Sacrilégio (profanar sacramentos, vasos sagrados, lugares consagrados a Deus)",
      "Receber a Santa Eucaristia em estado de pecado mortal",
      "Simonia (comprar ou vender coisas espirituais)",
      "Ateísmo ou agnosticismo (negar ou duvidar da existência de Deus)",
      "Apostasia (abandono completo da fé)",
      "Heresia (negar uma ou mais verdades da fé)",
      "Indiferentismo (acreditar que uma religião é tão boa quanto as demais)",
      "Ler ou fazer circular livros ou escritos contrários à fé Católica",
      "Tomar parte em culto herético ou cismático",
      "Aderir a grupos maçônicos ou outras sociedades proibidas (teosofia, rosa-cruz, etc.)",
      "Desespero da misericórdia de Deus",
      "Presunção da misericórdia de Deus para continuar no pecado",
    ],
  },
  {
    titulo: "II Mandamento",
    subtitulo: "Não tomarás o nome do Senhor em vão",
    itens: [
      "Desonra de Deus por uso profano ou desrespeitoso de seu Nome, ou do Santo Nome de Jesus Cristo, da Santíssima Virgem Maria e dos santos",
      "Blasfêmia (insultar a Deus, Nosso Senhor Jesus Cristo, a Igreja Católica, a Santíssima Virgem Maria ou os santos)",
      "Ouvir músicas blasfemas",
      "Perjúrio (prometer algo sob juramento sem ter intenção de cumpri-lo, ou quebrar promessa feita sob juramento)",
      "Fazer juramentos falsos ou desnecessários",
      "Amaldiçoar a si mesmo ou a outros (com intenção real)",
      "Murmurar, reclamando das disposições da providência divina",
      "Quebrar votos ou promessas feitas a Deus",
      "Irreverência na Igreja (falar durante a Missa sem razão, vestir-se de forma inapropriada, etc.)",
    ],
  },
  {
    titulo: "III Mandamento",
    subtitulo: "Lembra-te de santificar o dia do Senhor",
    itens: [
      "Omissão da oração e do culto divino",
      "Todo trabalho servil desnecessário no Domingo ou Dias Santos de Guarda",
      "Comércio desnecessário nos Domingos e Dias de Guarda",
      "Profanar estes dias com diversões pecaminosas, jogos de azar, dança indecente ou excessos com bebida",
    ],
  },
  {
    titulo: "IV Mandamento",
    subtitulo: "Honra teu pai e tua mãe",
    intro: "Para filhos: toda raiva ou aversão aos pais, desdenhar, ameaçar, afligir por ingratidão ou má conduta, desobedecer às suas ordens legítimas. Para pais: negligência na instrução religiosa dos filhos, dar escândalo, ser duro ou cruel nas correções, não conduzi-los à Missa. Para cônjuges: maltrato, negar-se ao débito conjugal sem causa justa, ciúmes despropositados, palavras injuriosas.",
    itens: [
      "Ódio, desprezo, ameaças ou violência contra os pais",
      "Não ajudar os pais em suas necessidades",
      "Desobediência às ordens legítimas dos pais",
      "Negligência dos pais na instrução religiosa dos filhos",
      "Adiar o batismo de uma criança (mais de um mês é, em geral, pecado mortal)",
      "Enviar filhos para escolas protestantes ou de outra religião",
      "Maltrato do cônjuge (sem consideração pelo bem-estar e caridade)",
      "Negar-se ao débito conjugal sem causa justa",
      "Palavras injuriosas entre cônjuges",
      "Desrespeito aos superiores espirituais (Papa, bispos, padres) em suas ordens legítimas",
      "Resistir às autoridades legais, tomar parte em violência de multidão",
      "Não pagar salários justos ou demitir empregados arbitrariamente",
      "Perda de tempo no trabalho (sobretudo com internet)",
      "Desobediência às leis civis e da Igreja",
    ],
  },
  {
    titulo: "V Mandamento",
    subtitulo: "Não matarás",
    itens: [
      "Causar morte ou lesão física de alguém por ação, participação, instigação, conselho ou consentimento",
      "Ter a intenção de matar alguém",
      "Assassinato",
      "Realizar um aborto, ajudar alguém a procurar um aborto (incorre em excomunhão se o aborto se consumar)",
      "Eutanásia ou retirar meios ordinários de um paciente terminal",
      "Suicídio ou tentativa de suicídio",
      "Brigar, rixas, ódio, desejo de vingança",
      "Tortura humana",
      "Gula (beber ou comer em excesso)",
      "Embriaguez",
      "Abuso de álcool, medicamentos ou drogas",
      "Colocar em perigo a vida de outros (beber e dirigir, dirigir muito rápido, etc.)",
      "Mutilação do corpo (vasectomia, ligadura de trompas — trata-se de pecado mortal)",
      "Inseminação artificial ou fertilização in vitro (trata-se de pecado mortal)",
      "Tomar contraceptivos abortivos ou de barreira (trata-se de pecado mortal)",
      "Mau exemplo ou escândalo, levando outros a pecar",
      "Recusar falar com outros ou ignorar ofertas de reconciliação",
      "Zombaria, escárnio, insultos, palavras irritantes",
      "Inveja pela prosperidade alheia, alegrar-se com a miséria alheia",
      "Vício em jogos de azar que coloca em perigo o sustento próprio ou da família",
      "Causar morte ou sofrimento desnecessário aos animais",
    ],
  },
  {
    titulo: "VI Mandamento",
    subtitulo: "Não cometerás adultério",
    intro: "Mencionar as circunstâncias que mudam a natureza do pecado: o sexo da outra pessoa, o parentesco, o estado (próprio e do outro) de casado, solteiro ou vinculado a um voto.",
    itens: [
      "Impureza e imodéstia nas palavras, nos olhares e nas ações",
      "Contar ou ouvir piadas sujas, falar ou ouvir coisas indecentes",
      "Vangloriar-se da própria imoralidade",
      "Utilizar roupas imodestas (minissaias, calças apertadas, decotes arrojados, biquínis, etc.)",
      "Comprar, alugar ou assistir filmes, programas ou ler material indecente",
      "Expor-se voluntariamente a ocasiões de pecado (companhia perigosa, locais perigosos, danças indecentes)",
      "Manter companhia pecaminosa ou morar com alguém que não é o cônjuge",
      "Ouvir música de letra indecente ou cujo ritmo favoreça a sensualidade",
      "Masturbação",
      "Fornicação (sexo antes do casamento)",
      "Prostituição",
      "Sodomia (práticas homossexuais)",
      "Outras práticas contrárias à natureza",
      "Adultério (também em pensamentos)",
      "Divórcio",
      "Incesto, abuso sexual, estupro",
      "Beijo sensual, prolongado; carícias fora do contexto do matrimônio",
      "Ato conjugal consumado de modo inapto à procriação",
      "Namoro sem tomar as devidas precauções para guardar a pureza e a fé",
    ],
  },
  {
    titulo: "VII Mandamento",
    subtitulo: "Não roubarás",
    intro: "É preciso dizer ao sacerdote o valor do que foi furtado/roubado ou a quantidade dos danos, de modo que o padre possa julgar se os pecados são mortais ou não. Sem a restituição ou firme propósito de fazê-la, o pecado não será perdoado.",
    itens: [
      "Roubo (quanto?)",
      "Pequenos furtos (tomar coisas do trabalho sem direito ou dinheiro da família sem permissão)",
      "Trapacear, plágio",
      "Quebra de regulamentação de direito autoral",
      "Manter consigo objetos emprestados ou perdidos sem tentar restituí-los",
      "Danificar por descuido ou malícia a propriedade alheia",
      "Sonegação de impostos justos",
      "Fraude comercial, desonestidade nos negócios",
      "Não pagar dívidas justas no tempo correto",
      "Usura (emprestar dinheiro a altos juros a alguém em dificuldade financeira)",
      "Corrupção, aceitar ou oferecer suborno",
      "Trabalho mal feito",
      "Pagar salários injustos ou desprover empregado de benefícios devidos",
      "Falsificação de cheques e faturas",
      "Despesas e gastos excessivos",
      "Jogar e apostar (privando-se dos meios necessários de vida)",
    ],
  },
  {
    titulo: "VIII Mandamento",
    subtitulo: "Não darás falso testemunho",
    itens: [
      "Mentir (a mentira chegou a prejudicar alguém?)",
      "Vangloriar-se, lisonja, hipocrisia, exagero",
      "Ironia, sarcasmo",
      "Detração (revelar faltas verdadeiras escondidas do próximo sem justa causa)",
      "Calúnia ou difamação (revelar falsos defeitos do próximo)",
      "Criticar os outros, escutar com prazer os outros sendo criticados",
      "Fofocas",
      "Desonrar injustamente outra pessoa em sua presença",
      "Julgamento precipitado (acreditar firmemente, sem razão, que alguém possui um defeito moral)",
      "Revelar segredos",
      "Recusar ou demorar em restituir o bom nome que foi manchado",
      "Acusações sem fundamento, suspeitas infundadas",
    ],
  },
  {
    titulo: "IX Mandamento",
    subtitulo: "Não cobiçarás a mulher do próximo",
    intro: "O nono mandamento proíbe todo pensamento e desejo impuro com os quais nos comprazemos deliberadamente. O penitente deve ter em mente que se deleitar deliberadamente em qualquer pecado do sexto mandamento pode ter o mesmo grau de gravidade de executá-lo de fato.",
    itens: [
      "Pensamentos e desejos impuros deliberadamente consentidos",
      "Comprazer-se voluntariamente em pensamentos de luxúria",
      "Consentir em paixões ou pensamentos impuros que vêm à mente",
    ],
  },
  {
    titulo: "X Mandamento",
    subtitulo: "Não cobiçarás os bens do próximo",
    itens: [
      "Inveja (desejar os bens de outrem)",
      "Ciúmes (zelo para manter um bem longe dos outros)",
      "Ganância e desejo sem limites de bens materiais (avareza)",
      "Desejo de enriquecer a qualquer preço",
      "Negócios que esperam circunstâncias desfavoráveis aos outros para lucrar",
      "Inveja dos sucessos, talentos, bens espirituais ou temporais alheios",
      "Desejar cometer injustiça prejudicando alguém para obter seus bens",
      "Alegrar-se ou consentir nos pecados contra o sétimo mandamento",
    ],
  },
  {
    titulo: "Preceitos da Santa Igreja",
    itens: [
      "I Preceito — Faltar à Santa Missa nos Domingos e Dias Santos de Guarda sem razão suficiente",
      "I Preceito — Chegar atrasado à Missa sem razão suficiente (dependendo da qualidade e quantidade do atraso, pode ser pecado leve ou grave)",
      "II Preceito — Não jejuar na Quarta-feira de Cinzas e Sexta-feira Santa (obriga dos 18 aos 59 anos)",
      "II Preceito — Não se abster de carne nas sextas-feiras e na Quarta-feira de Cinzas (obriga a partir dos 14 anos)",
      "III Preceito — Não se confessar de pecados mortais ao menos uma vez por ano",
      "IV Preceito — Não receber a Santa Comunhão durante o período da Páscoa (da Quinta-feira Santa até o Domingo da Santíssima Trindade)",
      "V Preceito — Não contribuir para o sustento da Igreja e de seus ministros conforme as próprias possibilidades",
      "VI Preceito — Casar-se ou ajudar alguém a se casar sem a permissão e forma devidas da Santa Igreja",
    ],
  },
]

export const ATO_DE_CONTRICAO = `Meu Deus,\neu me arrependo,\nde todo o coração,\nde Vos ter ofendido,\nporque sois tão bom e amável.\nPrometo, com a Vossa graça,\nesforçar-me para não mais pecar.\nMeu Jesus, Misericórdia.`

export const FORMULA_ABSOLVICAO = `Eu te absolvo de teus pecados em nome do Pai + e do Filho e do Espírito Santo. Amém.`
